# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Fast rendering of common datatypes"
HOMEPAGE="https://github.com/bos/blaze-textual"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="developer integer-simple +native"

RDEPEND=">=dev-haskell/blaze-builder-0.2.1.4:=[profile?]
	dev-haskell/old-locale:=[profile?]
	>=dev-haskell/text-0.11.0.2:=[profile?]
	dev-haskell/vector:=[profile?]
	>=dev-lang/ghc-8.4.3:=
	integer-simple? ( dev-haskell/integer-simple:=[profile?] )
	!native? ( >=dev-haskell/double-conversion-0.2.0.1:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
	test? ( >=dev-haskell/quickcheck-2.4.0.1
		>=dev-haskell/test-framework-0.3.3
		>=dev-haskell/test-framework-quickcheck2-0.2.9
		native? ( dev-haskell/double-conversion ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag developer developer) \
		$(cabal_flag integer-simple integer-simple) \
		$(cabal_flag native native)
}
